name: slikker_kit
description: Slikker Kit is a Flutter package which provides Slikker Design System components.
version: 1.0.1
homepage: https://github.com/AlexBesida/slikker_kit
repository: https://github.com/AlexBesida/slikker_kit

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
