name: slikker_kit
description: Slikker Kit is a Flutter package which provides Slikker Design System components.

version: 1.0.3

homepage: https://github.com/AlexBesida/slikker_kit
repository: https://github.com/AlexBesida/slikker_kit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
